version: '3.7'
services:
    backend:
        container_name: catalog
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        volumes:
            - .:/var/www/html
